### ISSUE TITLE
Missing lodash dependency

### ISSUE THREAD

**Issue by kevzettler** [srveit/riff-js#2]
```
kev@Kevs-MBP magica-voxel-parser $ node index.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kev/code/magica-voxel-parser/node_modules/riff-parser/riff/fmtChunk.js:6:14)
```

**Comment by srveit** [comment]
@kevzettler Thanks!
